# Generated by Django 3.1.4 on 2020-12-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writen_by', models.CharField(max_length=50)),
                ('is_public', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
