# Generated by Django 3.1.4 on 2020-12-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecriture', '0002_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
